/*
 ===================================================
 Author    : Abdel Rhman Helal Saleh
 File Name : ultrasonic.c
 Data      : Oct 12, 2023
 Time      : 8:06:07 PM
 ===================================================
 */
#include "ultrasonic.h"
#include <util/delay.h>
#include "../mcal/gpio.h"
#include "../mcal/icu.h"
uint16 g_ultrasonicRead = 0;
uint8 g_edgeCount = 0;
uint16 g_distance = 0;
/*Description
 ➢ Initialize the ICU driver as required.
 ➢ Setup the ICU call back function.
 ➢ Setup the direction for the trigger pin as output pin through the
 GPIO driver*/
void Ultrasonic_init(void) {
	/*config the Module*/
	ICU_ConfigType icu_init = { F_CPU_8, RAISING };
	ICU_init(&icu_init);
	/*call back the edge processing*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*trigger pin*/
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}
/*Description
 ➢ Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void) {
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);
	_delay_us(30);
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}
/*Description
 ➢ Send the trigger pulse by using Ultrasonic_Trigger function.
 ➢ Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void) {
	/*to trigger the ultrasonic*/
	Ultrasonic_Trigger();
	/*Distance = (TIMER value) / 58.8 cm
	 when Distance = 65 time should be 3822 in ideal mode
	 but in this program because some clock cycle waste at some function
	 when Distance = 65 time be 3759
	 -----------------------
	 65 -> 3822 (ideal mode)
	 65 -> 3759 (this code)
	 the difference (error) = 3822-3759 = 63
	 error % = 63/58.8 = 1
	 -----------------------
	 so we will add 1 to equ to skip error
	 */
	g_distance = (g_ultrasonicRead / 58) + 1;
	return g_distance;
}
/*Description
 ➢ This is the call back function called by the ICU driver.
 ➢ This is used to calculate the high time (pulse time) generated by
 the ultrasonic sensor*/
void Ultrasonic_edgeProcessing(void) {
	g_edgeCount++;
	if (g_edgeCount == 1) {
		/*Clear ICU*/
		ICU_clearTimerValue();
		/*start count the real time*/
		ICU_setEdgeDetectionType(FALLING);
	} else if (g_edgeCount == 2) {
		/* Store the High time value */
		g_ultrasonicRead = ICU_getInputCaptureValue();
		/*Clear ICU*/
		ICU_clearTimerValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
		/*recount the counter*/
		g_edgeCount = 0;

	}
}
