/*
 ===================================================
 Author    : Abdel Rhman Helal Saleh
 File Name : ultrasonic.h
 Data      : Oct 12, 2023
 Time      : 8:06:34 PM
 ===================================================
 */

#ifndef HAL_ULTRASONIC_H_
#define HAL_ULTRASONIC_H_

#include "../lib/std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define SOUND_VELOCITY (34000)
#define TIME_EXECUTION (1/1000000)
extern uint16 g_ultrasonicRead;
extern uint8 g_edgeCount;
extern uint16 g_distance;
/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/*Description
 ➢ Initialize the ICU driver as required.
 ➢ Setup the ICU call back function.
 ➢ Setup the direction for the trigger pin as output pin through the
 GPIO driver*/
void Ultrasonic_init(void);
/*Description
 ➢ Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*Description
 ➢ Send the trigger pulse by using Ultrasonic_Trigger function.
 ➢ Start the measurements by the ICU from this moment.*/
uint16 Ultrasonic_readDistance(void);
/*Description
 ➢ This is the call back function called by the ICU driver.
 ➢ This is used to calculate the high time (pulse time) generated by
 the ultrasonic sensor*/
void Ultrasonic_edgeProcessing(void);
#endif /* HAL_ULTRASONIC_H_ */
